### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by vinaykumar0409** [zigoo0/webpwn3r#9]
When I am trying to use scan.py it says "File "scan.py", line 11     print ga.green+'''           ^ SyntaxError: Missing parentheses in call to 'print'. Did you mean print(ga.green+''')?"

**Comment by zigoo0** [comment]
Hi, 

This is because you are using Python 3, while the tools is written in Python 2. Thus, using python 2 should solve the problem.

Thank you.
